//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GermanResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GermanResource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.LanguageResources.GermanResource", typeof(GermanResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konto bestätigt. Ihr Passwort wurde geändert.
        /// </summary>
        internal static string Account_confirmed__Your_password_has_been_changed {
            get {
                return ResourceManager.GetString("Account confirmed. Your password has been changed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kandidat erfolgreich erstellt.
        /// </summary>
        internal static string Candidate_created_successfully {
            get {
                return ResourceManager.GetString("Candidate created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kandidat erfolgreich gelöscht.
        /// </summary>
        internal static string Candidate_deleted_successfully {
            get {
                return ResourceManager.GetString("Candidate deleted successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kandidat erfolgreich aktualisiert.
        /// </summary>
        internal static string Candidate_updated_successfully {
            get {
                return ResourceManager.GetString("Candidate updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bestätigung fehlgeschlagen.
        /// </summary>
        internal static string Confirmation_failed {
            get {
                return ResourceManager.GetString("Confirmation failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mitarbeiter richtig zugeordnet.
        /// </summary>
        internal static string Employees_assigned_correctly {
            get {
                return ResourceManager.GetString("Employees assigned correctly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Hinzufügen einer Personalnotiz zum Kandidaten.
        /// </summary>
        internal static string Error_adding_HR_note_to_candidate {
            get {
                return ResourceManager.GetString("Error adding HR note to candidate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Hinzufügen des technischen Hinweises zum Kandidaten.
        /// </summary>
        internal static string Error_adding_tech_note_to_candidate {
            get {
                return ResourceManager.GetString("Error adding tech note to candidate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Zuweisen des Interviewdatums.
        /// </summary>
        internal static string Error_assigning_interview_date {
            get {
                return ResourceManager.GetString("Error assigning interview date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Zuweisen des Tech-Interview-Datums.
        /// </summary>
        internal static string Error_assigning_tech_interview_date {
            get {
                return ResourceManager.GetString("Error assigning tech interview date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Erstellen des Kandidaten (ungültige Einstellungs-ID).
        /// </summary>
        internal static string Error_creating_candidate__invalid_recruitmentId_ {
            get {
                return ResourceManager.GetString("Error creating candidate (invalid recruitmentId)", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Erstellen des Kandidaten (mindestens ein ungültiger Parameter).
        /// </summary>
        internal static string Error_creating_candidate__one_or_more_invalid_parameters_ {
            get {
                return ResourceManager.GetString("Error creating candidate (one or more invalid parameters)", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Erstellen des Interviews.
        /// </summary>
        internal static string Error_creating_interview {
            get {
                return ResourceManager.GetString("Error creating interview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Löschen des Kandidaten.
        /// </summary>
        internal static string Error_deleting_candidate {
            get {
                return ResourceManager.GetString("Error deleting candidate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Löschen des Interviews.
        /// </summary>
        internal static string Error_deleting_interview {
            get {
                return ResourceManager.GetString("Error deleting interview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Löschen der Rekrutierung.
        /// </summary>
        internal static string Error_deleting_recruitment {
            get {
                return ResourceManager.GetString("Error deleting recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Bearbeiten des Interviews.
        /// </summary>
        internal static string Error_editing_interview {
            get {
                return ResourceManager.GetString("Error editing interview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Beenden der Rekrutierung.
        /// </summary>
        internal static string Error_ending_recruitment {
            get {
                return ResourceManager.GetString("Error ending recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Abrufen des Kandidaten (falsche Parameter oder Kandidat existiert nicht).
        /// </summary>
        internal static string Error_getting_candidate__bad_parameters_or_candidate_doesn_t_exist_ {
            get {
                return ResourceManager.GetString("Error getting candidate (bad parameters or candidate doesn\'t exist)", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Abrufen der Liste der Rekrutierungen.
        /// </summary>
        internal static string Error_getting_list_of_recruitments {
            get {
                return ResourceManager.GetString("Error getting list of recruitments", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Speichern des Objekts in der Datenbank.
        /// </summary>
        internal static string Error_saving_object_to_database {
            get {
                return ResourceManager.GetString("Error saving object to database", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Aktualisieren des Kandidaten.
        /// </summary>
        internal static string Error_updating_candidate {
            get {
                return ResourceManager.GetString("Error updating candidate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Aktualisieren des Kandidaten bei der Zuweisung von Personalvermittlern.
        /// </summary>
        internal static string Error_updating_candidate_when_allocating_recruiters {
            get {
                return ResourceManager.GetString("Error updating candidate when allocating recruiters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fehler beim Aktualisieren der Rekrutierung.
        /// </summary>
        internal static string Error_updating_recruitment {
            get {
                return ResourceManager.GetString("Error updating recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Interview erfolgreich erstellt.
        /// </summary>
        internal static string Interview_created_successfully {
            get {
                return ResourceManager.GetString("Interview created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Interviewtermin richtig eingestellt.
        /// </summary>
        internal static string Interview_date_set_correctly {
            get {
                return ResourceManager.GetString("Interview date set correctly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Interview erfolgreich gelöscht.
        /// </summary>
        internal static string Interview_deleted_successfully {
            get {
                return ResourceManager.GetString("Interview deleted successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Interview erfolgreich bearbeitet.
        /// </summary>
        internal static string Interview_edited_successfully {
            get {
                return ResourceManager.GetString("Interview edited successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Interviewnotiz erfolgreich hinzugefügt.
        /// </summary>
        internal static string Interview_note_added_successfully {
            get {
                return ResourceManager.GetString("Interview note added successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No Interview with this Id.
        /// </summary>
        internal static string No_Interview_with_this_Id {
            get {
                return ResourceManager.GetString("No Interview with this Id", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kein Interview mit dieser ID.
        /// </summary>
        internal static string Password_Changed {
            get {
                return ResourceManager.GetString("Password Changed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiederherstellungs-E-Mail gesendet.
        /// </summary>
        internal static string Recovery_e_mail_sent {
            get {
                return ResourceManager.GetString("Recovery e-mail sent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekrutierung erfolgreich erstellt.
        /// </summary>
        internal static string Recruitment_created_successfully {
            get {
                return ResourceManager.GetString("Recruitment created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Einstellung erfolgreich gelöscht.
        /// </summary>
        internal static string Recruitment_deleted_successfully {
            get {
                return ResourceManager.GetString("Recruitment deleted successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekrutierung erfolgreich bearbeitet.
        /// </summary>
        internal static string Recruitment_edited_successfully {
            get {
                return ResourceManager.GetString("Recruitment edited successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rekrutierung erfolgreich beendet.
        /// </summary>
        internal static string Recruitment_ended_successfully {
            get {
                return ResourceManager.GetString("Recruitment ended successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fertigkeit erfolgreich hinzugefügt.
        /// </summary>
        internal static string Skill_added_successfully {
            get {
                return ResourceManager.GetString("Skill added successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fertigkeit erfolgreich gelöscht.
        /// </summary>
        internal static string Skill_deleted_successfully {
            get {
                return ResourceManager.GetString("Skill deleted successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fertigkeit erfolgreich aktualisiert.
        /// </summary>
        internal static string Skill_updated_successfully {
            get {
                return ResourceManager.GetString("Skill updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fertigkeit mit diesem Namen existiert bereits!.
        /// </summary>
        internal static string Skill_with_that_name_already_exists_ {
            get {
                return ResourceManager.GetString("Skill with that name already exists!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tech-Interview-Datum richtig eingestellt.
        /// </summary>
        internal static string Tech_interview_date_set_correctly {
            get {
                return ResourceManager.GetString("Tech interview date set correctly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tech-Interview-Notiz korrekt hinzugefügt.
        /// </summary>
        internal static string Tech_interview_note_added_correctly {
            get {
                return ResourceManager.GetString("Tech interview note added correctly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mit dieser ID findet keine Rekrutierung statt.
        /// </summary>
        internal static string There_is_no_recruitment_with_such_Id {
            get {
                return ResourceManager.GetString("There is no recruitment with such Id", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Benutzer existiert bereits.
        /// </summary>
        internal static string User_already_exists {
            get {
                return ResourceManager.GetString("User already exists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Benutzer und Guid haben nicht denselben Eigentümer.
        /// </summary>
        internal static string User_and_Guid_don_t_have_the_same_owner {
            get {
                return ResourceManager.GetString("User and Guid don\'t have the same owner", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Benutzer erfolgreich erstellt.
        /// </summary>
        internal static string User_created_successfully {
            get {
                return ResourceManager.GetString("User created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Falsche Anmeldeinformationen!.
        /// </summary>
        internal static string Wrong_credentials_ {
            get {
                return ResourceManager.GetString("Wrong credentials!", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Falschen Daten!.
        /// </summary>
        internal static string Wrong_data_ {
            get {
                return ResourceManager.GetString("Wrong data!", resourceCulture);
            }
        }
    }
}
